const starters = [
  "How do you see yourself?",
  "Is religion an important part of your life?",
  "Are you socially or politically engaged?",
  "Are you interested in raising kids someday?",
  "How did you spend your day?",
  "If you could get on a plane right now to anywhere in the world, where would you go?",
  "What’s something I wouldn’t guess about you?",
  "If work was no longer an option and you had plenty of money, what would you do all day?",
  "Who has been the most influential person in your life?",
  "If you were stranded on an island and could take three things with you, what would they be?",
  "What’s the most spontaneous thing you’ve ever done?",
  "What is your biggest pet peeve?",
  "How do you like to spend your mornings?",
  "How do you like to spend your nights?",
  "What are your quirks?",
  "What are you most afraid of?",
  "Tell me about your family",
  "What’s your favorite way to get active?",
  "How do you spend your free time?",
  "What’s your idea of a great morning?",
  "Do you consider yourself an introvert or extrovert?",
  "What is something you regularly buy that’s expensive but worth it?",
  "What assumptions do people often make about you that are wrong?",
  "What’s on your bucket list?",
  "What book can you read over and over again?",
  "If you could hop on a plane right now, where would you go?",
  "What's one thing you did as a kid that you miss most today?",
  "What sort of things make you laugh out loud?",
  "What kind of books do you like to read?",
  "What do you wish you were better at?",
  "What would you be doing if you weren’t in your current job?",
  "What’s the worst pickup line you’ve ever heard/dished out?",
  "Where can you see yourself living?",
  "Do you have any pets?",
  "What are you looking for in a partner?",
  "What takes your breath away?",
  "What is your favorite color?",
  "What is your favorite food?",
  "What's the scariest thing you've ever done?",
  "What are you most passionate about?",
  "Who do you talk to the most?",
  "What are your favorite sports?",
  "What are some of your favorite TV shows?",
  "What is your favorite animal?",
  "What’s your all-time favorite movie?",
  "If you were to patent an idea or thing, what would it be?",
  "What’s your favorite childhood memory?",
  "Did you have any nicknames growing up? Now?",
  "Do you have any hidden talents?",
  "If you could be known for one thing, what would you want to go down in history for?",
  "If you were to write a book, what would it be about?",
];

export default starters;
